### ISSUE TITLE
Rewriting History

### ISSUE THREAD

**Issue by ghost** [SethRobertson/GitFixUm#11]
Thanks to Seth for creating a well structured HTML document.

Reverse transcriptlaze:
# branch_overlay_merge#pushed_old#pushed#committed_really#committed#committedp#start

What about the case where whole files were comitted and pushed sometime back in the history. Suppose further that Git was only being used internally to the organisation and but now the entire repo is to be published, except for those few particular files that should not be published due to privacy concerns. Is there a clear and safe way in Git to handle this case and "rewrite hisory" because I'm _not_ a bad person? I don't want these files to be accessible even with reflog.

**Comment by ghost** [comment]
Innigo,
What you have requested goes against the "philosophy" of git -
each commit represents a change, and it relies on one or more previous commits.
If you try to "erase the memory of git" in regards to specific files, that means that
the commits that track the addition (and modification) of those files would have to be replaced by other commits,
and that, in turns, means that ALL the commits that follow them will have to be replaced as well.
You can do this and clear the reflog before uploading your repository to the remote site,
and you can also "start fresh" on the remote server, with the current snapshot of your files,
giving-up on the previous history of your repository
(i.e. you'll keep a private copy of your repository as it is now, then copy the current state of your work-area to a new location, delete any files you wish to keep for yourself, then create a new repository in the new location, and upload its content to the remote server).

**Comment by SethRobertson** [comment]
People creating a censored git repository for public distribution are doing something very different from what I was trying to go with this website.  Rewriting history is a good idea in this case, so go ahead and click the "bad person" button even though you are not.

Typically to erase whole files (eg files with internal passwords or keys or config or whatever) you would want to use git-filter-branch, as explained in this document.

Further, when you have additional commits in the future you want to "merge" into the public distribution, you will want to have a repo with both the private and public remotes in them.  You can then use git cherry-pick to pull the specific commits over (eg all commits since the last time you "merged").  I suggest making a tag in the private and public releases every time you do this "merge" since you have to track changes manually, then you can say `git cherry-pick previous-fake-merge-tag...master` or something like that to get all newer commits.  I say "merged" in quotes because a true merge would bring in the history with data you didn't want to expose.

This is all very annoying.  The "right" way to do this would be to have common branch with public and private branches off of it.  You can then make commits which should go to both places to the common branch and then merge those into the public and private branches.  public-only changes and private-only changes would be made on those branches and would never be merged back into common.  This works quite well, but has two major flaws:

1: You have to rewrite history on your current repository to have this new architecture.  This makes you a bad person, but sometimes bad is what you need.

2: It requires incredible discipline to make the commits on the correct branch.  Perhaps with a post-commit script and a simple policy you might be able to enforce this, but every time I've tried to do something like this, I invariably mess up within a few months and then need to rewrite history or cherry-pick or do something unfortunately.

Finally, you can do what gosheg suggested, create a brand new repo unrelated to what has happened before.  However, like in the first situation, you are manually tracking what has and has not been "merged" from the public to private repos and vis versa.
